#!/usr/bin/env bash

#
# jontas@gmx.com (2024)
# SPDX-License-Identifier: MIT

MONITOR="eDP-1"
WALLPAPER_DIR="$HOME/Pictures/wallpapers"

# Chose a random wallpaper
WALLPAPER=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)

# Clear and add new wallpaper
hyprctl hyprpaper unload all
hyprctl hyprpaper preload "$WALLPAPER"
hyprctl hyprpaper wallpaper "$MONITOR,$WALLPAPER"

