name = "ai"
name_pretty = "AI"
icon = "/home/jontas/.local/share/icons/ai/ai-generic.png"
global_search = false
action = "/opt/brave.com/brave-beta/brave-browser-beta --profile-directory=Default --app=%VALUE%"

[[entries]]
text = "ChatGPT"
icon = "/home/jontas/.local/share/icons/ai/chatgpt-ai.svg"
value = "https://chatgpt.com/"

[[entries]]
text = "Gemini"
icon = "/home/jontas/.local/share/icons/ai/gemini-ai.svg"
value = "https://gemini.google.com/app"

[[entries]]
text = "Grok"
icon = "/home/jontas/.local/share/icons/ai/grok-ai.svg"
value = "https://grok.com/"

[[entries]]
text = "Grok Tasks"
icon = "/home/jontas/.local/share/icons/ai/grok-ai.svg"
value = "https://grok.com/tasks"


[[entries]]
text = "Claude"
icon = "/home/jontas/.local/share/icons/ai/claude-ai.png"
value = "https://claude.ai/new"

[[entries]]
text = "Perplexity"
icon = "/home/jontas/.local/share/icons/ai/perplexity-ai.png"
value = "https://www.perplexity.ai/"
