name = "ai"
name_pretty = "AI"
icon = "/home/jontas/.local/share/icons/ai/ai-generic.png"
global_search = false
action = "/opt/brave.com/brave-beta/brave-browser-beta --profile-directory=Default --app=%VALUE%"

[[entries]]
text = "ChatGPT"
icon = "/home/jontas/.local/share/icons/ai/chatgpt.svg"
value = "https://chatgpt.com/"

[[entries]]
text = "Deepseek"
icon = "/home/jontas/.local/share/icons/ai/deepseek.svg"
value = "https://chat.deepseek.com/"

[[entries]]
text = "Gemini"
icon = "/home/jontas/.local/share/icons/ai/gemini.svg"
value = "https://gemini.google.com/app"

[[entries]]
text = "Grok"
icon = "/home/jontas/.local/share/icons/ai/grok.svg"
value = "https://grok.com/"

[[entries]]
text = "Copilot"
icon = "/home/jontas/.local/share/icons/ai/copilot.svg"
value = "https://copilot.microsoft.com/"


[[entries]]
text = "Claude"
icon = "/home/jontas/.local/share/icons/ai/claude.png"
value = "https://claude.ai/new"

[[entries]]
text = "Perplexity"
icon = "/home/jontas/.local/share/icons/ai/perplexity.png"
value = "https://www.perplexity.ai/"
